// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package Proto_Proxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 错误码
type STATUS int32

const (
	// 0~99, 通用错误码
	STATUS_OK            STATUS = 0
	STATUS_UNKNOWN_ERROR STATUS = 1
	STATUS_NOT_AUTH      STATUS = 2
	STATUS_TOKEN_INVALID STATUS = 3
	STATUS_INSUFFICIENT  STATUS = 4
	STATUS_REDIRECT      STATUS = 5
	STATUS_IDLE_TIMEOUT  STATUS = 6
	STATUS_DUP_LOGIN     STATUS = 7
	STATUS_PARAM_ERROR   STATUS = 8
	STATUS_SERVER_CLOSED STATUS = 9
	// 200-299 cube错误码
	STATUS_CUBE_BANKER_INSUFFICIENT   STATUS = 200
	STATUS_CUBE_BANKER_FULL           STATUS = 201
	STATUS_CUBE_CHIP_ERROR            STATUS = 202
	STATUS_CUBE_BET_OVER_LIMIT        STATUS = 203
	STATUS_CUBE_OFF_BANKER_FOR_CREDIT STATUS = 204
	STATUS_CUBE_OFF_BANKER_FOR_COUNT  STATUS = 205
	STATUS_CUBE_BET_OVER_CREDIT       STATUS = 206
)

var STATUS_name = map[int32]string{
	0:   "OK",
	1:   "UNKNOWN_ERROR",
	2:   "NOT_AUTH",
	3:   "TOKEN_INVALID",
	4:   "INSUFFICIENT",
	5:   "REDIRECT",
	6:   "IDLE_TIMEOUT",
	7:   "DUP_LOGIN",
	8:   "PARAM_ERROR",
	9:   "SERVER_CLOSED",
	200: "CUBE_BANKER_INSUFFICIENT",
	201: "CUBE_BANKER_FULL",
	202: "CUBE_CHIP_ERROR",
	203: "CUBE_BET_OVER_LIMIT",
	204: "CUBE_OFF_BANKER_FOR_CREDIT",
	205: "CUBE_OFF_BANKER_FOR_COUNT",
	206: "CUBE_BET_OVER_CREDIT",
}
var STATUS_value = map[string]int32{
	"OK":                         0,
	"UNKNOWN_ERROR":              1,
	"NOT_AUTH":                   2,
	"TOKEN_INVALID":              3,
	"INSUFFICIENT":               4,
	"REDIRECT":                   5,
	"IDLE_TIMEOUT":               6,
	"DUP_LOGIN":                  7,
	"PARAM_ERROR":                8,
	"SERVER_CLOSED":              9,
	"CUBE_BANKER_INSUFFICIENT":   200,
	"CUBE_BANKER_FULL":           201,
	"CUBE_CHIP_ERROR":            202,
	"CUBE_BET_OVER_LIMIT":        203,
	"CUBE_OFF_BANKER_FOR_CREDIT": 204,
	"CUBE_OFF_BANKER_FOR_COUNT":  205,
	"CUBE_BET_OVER_CREDIT":       206,
}

func (x STATUS) String() string {
	return proto.EnumName(STATUS_name, int32(x))
}
func (STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_msg_4b2ec394d9cf017c, []int{0}
}

// 对时，服务端存活探测探测, id=0
type Ping struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_4b2ec394d9cf017c, []int{0}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (dst *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(dst, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// 对时，服务端返回当前时间，id=99
type Pong struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_4b2ec394d9cf017c, []int{1}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (dst *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(dst, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// 错误信息，id: 100
type ErrorST struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp"`
	Status               STATUS   `protobuf:"varint,2,opt,name=Status,proto3,enum=proto.STATUS" json:"Status"`
	Msg                  string   `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorST) Reset()         { *m = ErrorST{} }
func (m *ErrorST) String() string { return proto.CompactTextString(m) }
func (*ErrorST) ProtoMessage()    {}
func (*ErrorST) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_4b2ec394d9cf017c, []int{2}
}
func (m *ErrorST) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorST.Unmarshal(m, b)
}
func (m *ErrorST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorST.Marshal(b, m, deterministic)
}
func (dst *ErrorST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorST.Merge(dst, src)
}
func (m *ErrorST) XXX_Size() int {
	return xxx_messageInfo_ErrorST.Size(m)
}
func (m *ErrorST) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorST.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorST proto.InternalMessageInfo

func (m *ErrorST) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ErrorST) GetStatus() STATUS {
	if m != nil {
		return m.Status
	}
	return STATUS_OK
}

func (m *ErrorST) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Ping)(nil), "proto.Ping")
	proto.RegisterType((*Pong)(nil), "proto.Pong")
	proto.RegisterType((*ErrorST)(nil), "proto.ErrorST")
	proto.RegisterEnum("proto.STATUS", STATUS_name, STATUS_value)
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_msg_4b2ec394d9cf017c) }

var fileDescriptor_msg_4b2ec394d9cf017c = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcd, 0x6e, 0xd4, 0x30,
	0x14, 0x85, 0x71, 0xd2, 0xa6, 0xcd, 0xa5, 0x43, 0x2f, 0x97, 0x22, 0xa5, 0x88, 0x9f, 0x11, 0x02,
	0x69, 0xc4, 0xa2, 0x0b, 0x78, 0x82, 0x34, 0x71, 0xa8, 0x95, 0xc4, 0x8e, 0x1c, 0xbb, 0x2c, 0xcd,
	0x20, 0xa1, 0xd1, 0x2c, 0x86, 0x8c, 0x92, 0xf0, 0x8e, 0xfc, 0xbf, 0x08, 0x2f, 0x81, 0x92, 0x89,
	0x80, 0x91, 0x10, 0x5d, 0xd9, 0xba, 0xe7, 0x3b, 0xe7, 0xd8, 0xba, 0x10, 0x6e, 0xba, 0xd5, 0xc5,
	0xb6, 0x6d, 0xfa, 0x86, 0x0e, 0xc7, 0xe3, 0xe9, 0x33, 0x38, 0xa8, 0xd6, 0x1f, 0x56, 0xf4, 0x10,
	0x42, 0xb3, 0xde, 0xbc, 0xef, 0xfa, 0xe5, 0x66, 0x1b, 0xb1, 0x39, 0x5b, 0xf8, 0xfa, 0xcf, 0x60,
	0xa4, 0x9a, 0x1b, 0xa9, 0xb7, 0x70, 0xc4, 0xdb, 0xb6, 0x69, 0x6b, 0xf3, 0x7f, 0x90, 0x9e, 0x43,
	0x50, 0xf7, 0xcb, 0xfe, 0x63, 0x17, 0x79, 0x73, 0xb6, 0xb8, 0xf3, 0x72, 0xb6, 0x7b, 0xd3, 0x45,
	0x6d, 0x62, 0x63, 0x6b, 0x3d, 0x89, 0x84, 0xe0, 0x97, 0xdd, 0x2a, 0xf2, 0xe7, 0x6c, 0x11, 0xea,
	0xe1, 0xfa, 0xe2, 0xa7, 0x07, 0xc1, 0x0e, 0xa2, 0x00, 0x3c, 0x95, 0xe3, 0x2d, 0xba, 0x0b, 0x33,
	0x2b, 0x73, 0xa9, 0xde, 0x48, 0xc7, 0xb5, 0x56, 0x1a, 0x19, 0x9d, 0xc0, 0xb1, 0x54, 0xc6, 0xc5,
	0xd6, 0x5c, 0xa1, 0x37, 0x00, 0x46, 0xe5, 0x5c, 0x3a, 0x21, 0xaf, 0xe3, 0x42, 0xa4, 0xe8, 0x13,
	0xc2, 0x89, 0x90, 0xb5, 0xcd, 0x32, 0x91, 0x08, 0x2e, 0x0d, 0x1e, 0x0c, 0x16, 0xcd, 0x53, 0xa1,
	0x79, 0x62, 0xf0, 0x70, 0xd4, 0xd3, 0x82, 0x3b, 0x23, 0x4a, 0xae, 0xac, 0xc1, 0x80, 0x66, 0x10,
	0xa6, 0xb6, 0x72, 0x85, 0x7a, 0x2d, 0x24, 0x1e, 0xd1, 0x29, 0xdc, 0xae, 0x62, 0x1d, 0x97, 0x53,
	0xe5, 0xf1, 0x50, 0x52, 0x73, 0x7d, 0xcd, 0xb5, 0x4b, 0x0a, 0x55, 0xf3, 0x14, 0x43, 0x7a, 0x04,
	0x51, 0x62, 0x2f, 0xb9, 0xbb, 0x8c, 0x65, 0xce, 0xb5, 0xdb, 0x2b, 0xfc, 0xc4, 0xe8, 0x3e, 0xe0,
	0xdf, 0x72, 0x66, 0x8b, 0x02, 0x3f, 0x33, 0x3a, 0x83, 0xd3, 0x71, 0x9c, 0x5c, 0x89, 0x6a, 0x4a,
	0xff, 0xc2, 0x28, 0x82, 0x7b, 0x3b, 0x98, 0x1b, 0xa7, 0x86, 0x96, 0x42, 0x94, 0xc2, 0xe0, 0x57,
	0x46, 0x4f, 0xe0, 0xc1, 0xa8, 0xa8, 0x2c, 0xfb, 0x1d, 0xa5, 0xb4, 0x4b, 0x86, 0xdf, 0x18, 0xfc,
	0xc6, 0xe8, 0x31, 0x9c, 0xff, 0x13, 0x50, 0x56, 0x1a, 0xfc, 0xce, 0xe8, 0x1c, 0xce, 0xf6, 0xa3,
	0x27, 0xeb, 0x0f, 0xf6, 0x2e, 0x18, 0xb7, 0xf2, 0xea, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a,
	0xb6, 0x79, 0x27, 0x36, 0x02, 0x00, 0x00,
}
