// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.2
// source: Proto_Proxy.proto

package Proto_Proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proxy_CMD int32

const (
	Proxy_C2P_Connect  Proxy_CMD = 0 // 客户端链接代理
	Proxy_P2C_Connect  Proxy_CMD = 1 // 代理确认链接客户端
	Proxy_C2P_SendData Proxy_CMD = 2 // 客户端向代理发送消息
	Proxy_P2C_SendData Proxy_CMD = 3 // 代理向客户端发送消息
	Proxy_S2P_Connect  Proxy_CMD = 4 // 服务器连接代理
	Proxy_P2S_Connect  Proxy_CMD = 5 // 代理确认链接服务器
	Proxy_S2P_SendData Proxy_CMD = 6 // 服务器向代理发数据
	Proxy_P2S_SendData Proxy_CMD = 7 // 代理向服务器发送
)

// Enum value maps for Proxy_CMD.
var (
	Proxy_CMD_name = map[int32]string{
		0: "C2P_Connect",
		1: "P2C_Connect",
		2: "C2P_SendData",
		3: "P2C_SendData",
		4: "S2P_Connect",
		5: "P2S_Connect",
		6: "S2P_SendData",
		7: "P2S_SendData",
	}
	Proxy_CMD_value = map[string]int32{
		"C2P_Connect":  0,
		"P2C_Connect":  1,
		"C2P_SendData": 2,
		"P2C_SendData": 3,
		"S2P_Connect":  4,
		"P2S_Connect":  5,
		"S2P_SendData": 6,
		"P2S_SendData": 7,
	}
)

func (x Proxy_CMD) Enum() *Proxy_CMD {
	p := new(Proxy_CMD)
	*p = x
	return p
}

func (x Proxy_CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Proxy_CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_Proto_Proxy_proto_enumTypes[0].Descriptor()
}

func (Proxy_CMD) Type() protoreflect.EnumType {
	return &file_Proto_Proxy_proto_enumTypes[0]
}

func (x Proxy_CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Proxy_CMD.Descriptor instead.
func (Proxy_CMD) EnumDescriptor() ([]byte, []int) {
	return file_Proto_Proxy_proto_rawDescGZIP(), []int{0, 0}
}

type Proxy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_Proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_Proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_Proto_Proxy_proto_rawDescGZIP(), []int{0}
}

// (client/server)向代理服发送数据
type ProxyC2S_SendData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol    int32  `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`   // 协议
	Protocol2   int32  `protobuf:"varint,2,opt,name=protocol2,proto3" json:"protocol2,omitempty"` // 协议
	OpenId      string `protobuf:"bytes,3,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	ServerId    string `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	PackageData []byte `protobuf:"bytes,5,opt,name=package_data,json=packageData,proto3" json:"package_data,omitempty"` // 二进制数据类型
}

func (x *ProxyC2S_SendData) Reset() {
	*x = ProxyC2S_SendData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_Proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyC2S_SendData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyC2S_SendData) ProtoMessage() {}

func (x *ProxyC2S_SendData) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_Proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyC2S_SendData.ProtoReflect.Descriptor instead.
func (*ProxyC2S_SendData) Descriptor() ([]byte, []int) {
	return file_Proto_Proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyC2S_SendData) GetProtocol() int32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *ProxyC2S_SendData) GetProtocol2() int32 {
	if x != nil {
		return x.Protocol2
	}
	return 0
}

func (x *ProxyC2S_SendData) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *ProxyC2S_SendData) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ProxyC2S_SendData) GetPackageData() []byte {
	if x != nil {
		return x.PackageData
	}
	return nil
}

// 代理服向(client/server)回数据
type ProxyS2C_SendData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol    int32  `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`   // 协议
	Protocol2   int32  `protobuf:"varint,2,opt,name=protocol2,proto3" json:"protocol2,omitempty"` // 协议
	OpenId      string `protobuf:"bytes,3,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	PackageData []byte `protobuf:"bytes,4,opt,name=package_data,json=packageData,proto3" json:"package_data,omitempty"` // 二进制数据类型
}

func (x *ProxyS2C_SendData) Reset() {
	*x = ProxyS2C_SendData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_Proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyS2C_SendData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyS2C_SendData) ProtoMessage() {}

func (x *ProxyS2C_SendData) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_Proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyS2C_SendData.ProtoReflect.Descriptor instead.
func (*ProxyS2C_SendData) Descriptor() ([]byte, []int) {
	return file_Proto_Proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyS2C_SendData) GetProtocol() int32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *ProxyS2C_SendData) GetProtocol2() int32 {
	if x != nil {
		return x.Protocol2
	}
	return 0
}

func (x *ProxyS2C_SendData) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *ProxyS2C_SendData) GetPackageData() []byte {
	if x != nil {
		return x.PackageData
	}
	return nil
}

var File_Proto_Proxy_proto protoreflect.FileDescriptor

var file_Proto_Proxy_proto_rawDesc = []byte{
	0x0a, 0x11, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x22, 0x91, 0x01,
	0x0a, 0x03, 0x43, 0x4d, 0x44, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x32, 0x50, 0x5f, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x32, 0x43, 0x5f, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x32, 0x50, 0x5f, 0x53,
	0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x32, 0x43,
	0x5f, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x53,
	0x32, 0x50, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b,
	0x50, 0x32, 0x53, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x10, 0x05, 0x12, 0x10, 0x0a,
	0x0c, 0x53, 0x32, 0x50, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x10, 0x06, 0x12,
	0x10, 0x0a, 0x0c, 0x50, 0x32, 0x53, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x10,
	0x07, 0x22, 0xa6, 0x01, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x32, 0x53, 0x5f, 0x53,
	0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x32,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x32, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x89, 0x01, 0x0a, 0x11, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x53, 0x32, 0x43, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x32, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70,
	0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65,
	0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Proto_Proxy_proto_rawDescOnce sync.Once
	file_Proto_Proxy_proto_rawDescData = file_Proto_Proxy_proto_rawDesc
)

func file_Proto_Proxy_proto_rawDescGZIP() []byte {
	file_Proto_Proxy_proto_rawDescOnce.Do(func() {
		file_Proto_Proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_Proto_Proxy_proto_rawDescData)
	})
	return file_Proto_Proxy_proto_rawDescData
}

var file_Proto_Proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Proto_Proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Proto_Proxy_proto_goTypes = []interface{}{
	(Proxy_CMD)(0),            // 0: Proxy.CMD
	(*Proxy)(nil),             // 1: Proxy
	(*ProxyC2S_SendData)(nil), // 2: ProxyC2S_SendData
	(*ProxyS2C_SendData)(nil), // 3: ProxyS2C_SendData
}
var file_Proto_Proxy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Proto_Proxy_proto_init() }
func file_Proto_Proxy_proto_init() {
	if File_Proto_Proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Proto_Proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proxy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_Proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyC2S_SendData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_Proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyS2C_SendData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_Proxy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Proto_Proxy_proto_goTypes,
		DependencyIndexes: file_Proto_Proxy_proto_depIdxs,
		EnumInfos:         file_Proto_Proxy_proto_enumTypes,
		MessageInfos:      file_Proto_Proxy_proto_msgTypes,
	}.Build()
	File_Proto_Proxy_proto = out.File
	file_Proto_Proxy_proto_rawDesc = nil
	file_Proto_Proxy_proto_goTypes = nil
	file_Proto_Proxy_proto_depIdxs = nil
}
